import { Product, Warehouse, Supplier, Receipt, Delivery, Transfer, Adjustment } from '@/types';

export const initialWarehouses: Warehouse[] = [
  {
    id: 'wh1',
    name: 'Main Warehouse',
    code: 'WH-001',
    address: '123 Industrial Park, Manufacturing District',
  },
  {
    id: 'wh2',
    name: 'North Distribution Center',
    code: 'WH-002',
    address: '456 Commerce Ave, Business Park North',
  },
  {
    id: 'wh3',
    name: 'South Fulfillment Hub',
    code: 'WH-003',
    address: '789 Logistics Blvd, Distribution Zone',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup1',
    name: 'Global Parts Co.',
    email: 'orders@globalparts.com',
    phone: '+1 (555) 123-4567',
  },
  {
    id: 'sup2',
    name: 'Premium Components Ltd.',
    email: 'sales@premiumcomp.com',
    phone: '+1 (555) 234-5678',
  },
  {
    id: 'sup3',
    name: 'Industrial Supplies Inc.',
    email: 'contact@indsupplies.com',
    phone: '+1 (555) 345-6789',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod1',
    name: 'Industrial Bolt M12x50',
    sku: 'BOLT-M12-50',
    category: 'Hardware',
    unitOfMeasure: 'pieces',
    stock: { wh1: 500, wh2: 300, wh3: 200 },
    minStock: 100,
    maxStock: 1000,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'prod2',
    name: 'Hydraulic Pump HP-2000',
    sku: 'PUMP-HP-2K',
    category: 'Machinery',
    unitOfMeasure: 'units',
    stock: { wh1: 3, wh2: 2, wh3: 1 },
    minStock: 5,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'prod3',
    name: 'Steel Plate 10mm',
    sku: 'STEEL-10MM',
    category: 'Raw Materials',
    unitOfMeasure: 'sheets',
    stock: { wh1: 85, wh2: 45, wh3: 60 },
    minStock: 20,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'prod4',
    name: 'Safety Helmet Industrial',
    sku: 'SAFE-HELM-01',
    category: 'Safety Equipment',
    unitOfMeasure: 'pieces',
    stock: { wh1: 150, wh2: 100, wh3: 80 },
    minStock: 50,
    maxStock: 200,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'prod5',
    name: 'Electric Motor 3HP',
    sku: 'MOTOR-3HP',
    category: 'Machinery',
    unitOfMeasure: 'units',
    stock: { wh1: 25, wh2: 10, wh3: 15 },
    minStock: 8,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'prod6',
    name: 'Rubber Gasket Set',
    sku: 'GASKET-RUB-SET',
    category: 'Hardware',
    unitOfMeasure: 'sets',
    stock: { wh1: 220, wh2: 180, wh3: 140 },
    minStock: 100,
    maxStock: 300,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'prod7',
    name: 'Industrial Lubricant 5L',
    sku: 'LUB-IND-5L',
    category: 'Chemicals',
    unitOfMeasure: 'bottles',
    stock: { wh1: 95, wh2: 65, wh3: 75 },
    minStock: 40,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'prod8',
    name: 'Cable Reel 100m',
    sku: 'CABLE-100M',
    category: 'Electrical',
    unitOfMeasure: 'reels',
    stock: { wh1: 42, wh2: 28, wh3: 35 },
    minStock: 15,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
  {
    id: 'prod9',
    name: 'Welding Rod E6013',
    sku: 'WELD-E6013',
    category: 'Consumables',
    unitOfMeasure: 'kg',
    stock: { wh1: 180, wh2: 120, wh3: 95 },
    minStock: 50,
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-12'),
  },
  {
    id: 'prod10',
    name: 'Pneumatic Valve V-100',
    sku: 'VALVE-V100',
    category: 'Machinery',
    unitOfMeasure: 'units',
    stock: { wh1: 32, wh2: 18, wh3: 24 },
    minStock: 10,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const initialReceipts: Receipt[] = [
  {
    id: 'rec1',
    supplierId: 'sup1',
    warehouseId: 'wh1',
    status: 'draft',
    lines: [
      { productId: 'prod1', quantity: 100 },
      { productId: 'prod3', quantity: 50 },
    ],
    notes: 'Initial stock receipt from Global Parts Co.',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'rec2',
    supplierId: 'sup2',
    warehouseId: 'wh2',
    status: 'waiting',
    lines: [
      { productId: 'prod2', quantity: 5 },
      { productId: 'prod5', quantity: 10 },
    ],
    notes: 'Waiting for quality inspection',
    createdAt: new Date('2024-03-02'),
    updatedAt: new Date('2024-03-02'),
  },
  {
    id: 'rec3',
    supplierId: 'sup3',
    warehouseId: 'wh1',
    status: 'ready',
    lines: [
      { productId: 'prod4', quantity: 75 },
      { productId: 'prod7', quantity: 30 },
    ],
    notes: 'Ready for validation',
    createdAt: new Date('2024-03-03'),
    updatedAt: new Date('2024-03-03'),
  },
  {
    id: 'rec4',
    supplierId: 'sup1',
    warehouseId: 'wh3',
    status: 'done',
    lines: [
      { productId: 'prod6', quantity: 50 },
      { productId: 'prod8', quantity: 20 },
    ],
    notes: 'Completed receipt',
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-02-28'),
  },
];

export const initialDeliveries: Delivery[] = [
  {
    id: 'del1',
    warehouseId: 'wh1',
    status: 'draft',
    customerName: 'ABC Manufacturing',
    lines: [
      { productId: 'prod1', quantity: 50 },
      { productId: 'prod3', quantity: 25 },
    ],
    notes: 'Pending customer confirmation',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'del2',
    warehouseId: 'wh2',
    status: 'waiting',
    customerName: 'XYZ Industries',
    lines: [
      { productId: 'prod2', quantity: 3 },
      { productId: 'prod5', quantity: 5 },
    ],
    notes: 'Items picked, waiting for packing',
    createdAt: new Date('2024-03-02'),
    updatedAt: new Date('2024-03-02'),
  },
  {
    id: 'del3',
    warehouseId: 'wh1',
    status: 'ready',
    customerName: 'Tech Solutions Inc.',
    lines: [
      { productId: 'prod4', quantity: 30 },
      { productId: 'prod7', quantity: 15 },
    ],
    notes: 'Packed and ready for shipment',
    createdAt: new Date('2024-03-03'),
    updatedAt: new Date('2024-03-03'),
  },
  {
    id: 'del4',
    warehouseId: 'wh3',
    status: 'done',
    customerName: 'Global Industries',
    lines: [
      { productId: 'prod6', quantity: 20 },
      { productId: 'prod8', quantity: 10 },
    ],
    notes: 'Delivered successfully',
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'del5',
    warehouseId: 'wh1',
    status: 'done',
    customerName: 'Manufacturing Corp',
    lines: [
      { productId: 'prod1', quantity: 150 },
      { productId: 'prod3', quantity: 40 },
    ],
    notes: 'Completed delivery',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'del6',
    warehouseId: 'wh1',
    status: 'done',
    customerName: 'Industrial Supplies',
    lines: [
      { productId: 'prod1', quantity: 200 },
      { productId: 'prod4', quantity: 50 },
    ],
    notes: 'Delivered',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'del7',
    warehouseId: 'wh2',
    status: 'done',
    customerName: 'Tech Solutions',
    lines: [
      { productId: 'prod2', quantity: 5 },
      { productId: 'prod5', quantity: 8 },
    ],
    notes: 'Completed',
    createdAt: new Date('2024-02-22'),
    updatedAt: new Date('2024-02-22'),
  },
];

export const initialTransfers: Transfer[] = [
  {
    id: 'trf1',
    fromWarehouseId: 'wh1',
    toWarehouseId: 'wh2',
    status: 'draft',
    lines: [
      { productId: 'prod1', quantity: 100 },
      { productId: 'prod3', quantity: 30 },
    ],
    notes: 'Transfer to North Distribution Center',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'trf2',
    fromWarehouseId: 'wh2',
    toWarehouseId: 'wh3',
    status: 'waiting',
    lines: [
      { productId: 'prod2', quantity: 2 },
      { productId: 'prod5', quantity: 3 },
    ],
    notes: 'Waiting for transport',
    createdAt: new Date('2024-03-02'),
    updatedAt: new Date('2024-03-02'),
  },
  {
    id: 'trf3',
    fromWarehouseId: 'wh1',
    toWarehouseId: 'wh3',
    status: 'ready',
    lines: [
      { productId: 'prod4', quantity: 25 },
      { productId: 'prod7', quantity: 20 },
    ],
    notes: 'Ready for transfer',
    createdAt: new Date('2024-03-03'),
    updatedAt: new Date('2024-03-03'),
  },
  {
    id: 'trf4',
    fromWarehouseId: 'wh3',
    toWarehouseId: 'wh1',
    status: 'done',
    lines: [
      { productId: 'prod6', quantity: 15 },
      { productId: 'prod8', quantity: 8 },
    ],
    notes: 'Transfer completed',
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-02-28'),
  },
];

export const initialAdjustments: Adjustment[] = [
  {
    id: 'adj1',
    warehouseId: 'wh1',
    status: 'draft',
    lines: [
      {
        productId: 'prod1',
        countedQuantity: 520,
        systemQuantity: 500,
        difference: 20,
        reason: 'Found extra units during count',
      },
      {
        productId: 'prod3',
        countedQuantity: 80,
        systemQuantity: 85,
        difference: -5,
        reason: 'Damaged items found',
      },
    ],
    notes: 'Monthly inventory count - Main Warehouse',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'adj2',
    warehouseId: 'wh2',
    status: 'waiting',
    lines: [
      {
        productId: 'prod2',
        countedQuantity: 10,
        systemQuantity: 8,
        difference: 2,
        reason: 'Unrecorded receipt',
      },
      {
        productId: 'prod5',
        countedQuantity: 12,
        systemQuantity: 10,
        difference: 2,
        reason: 'Stock found in wrong location',
      },
    ],
    notes: 'Quarterly audit - North Distribution Center',
    createdAt: new Date('2024-03-02'),
    updatedAt: new Date('2024-03-02'),
  },
  {
    id: 'adj3',
    warehouseId: 'wh3',
    status: 'ready',
    lines: [
      {
        productId: 'prod4',
        countedQuantity: 85,
        systemQuantity: 80,
        difference: 5,
        reason: 'Physical count adjustment',
      },
      {
        productId: 'prod7',
        countedQuantity: 70,
        systemQuantity: 75,
        difference: -5,
        reason: 'Expired items removed',
      },
    ],
    notes: 'Ready for approval',
    createdAt: new Date('2024-03-03'),
    updatedAt: new Date('2024-03-03'),
  },
  {
    id: 'adj4',
    warehouseId: 'wh1',
    status: 'done',
    lines: [
      {
        productId: 'prod6',
        countedQuantity: 225,
        systemQuantity: 220,
        difference: 5,
        reason: 'Completed adjustment',
      },
    ],
    notes: 'Adjustment completed and stock updated',
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-02-28'),
  },
];
