import { Product, Warehouse, Supplier, Delivery, Transfer } from '@/types';

export const initialWarehouses: Warehouse[] = [
  {
    id: 'wh1',
    name: 'Main Warehouse',
    code: 'WH-001',
    address: '123 Industrial Park, Manufacturing District',
  },
  {
    id: 'wh2',
    name: 'North Distribution Center',
    code: 'WH-002',
    address: '456 Commerce Ave, Business Park North',
  },
  {
    id: 'wh3',
    name: 'South Fulfillment Hub',
    code: 'WH-003',
    address: '789 Logistics Blvd, Distribution Zone',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup1',
    name: 'Global Parts Co.',
    email: 'orders@globalparts.com',
    phone: '+1 (555) 123-4567',
  },
  {
    id: 'sup2',
    name: 'Premium Components Ltd.',
    email: 'sales@premiumcomp.com',
    phone: '+1 (555) 234-5678',
  },
  {
    id: 'sup3',
    name: 'Industrial Supplies Inc.',
    email: 'contact@indsupplies.com',
    phone: '+1 (555) 345-6789',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod1',
    name: 'Industrial Bolt M12x50',
    sku: 'BOLT-M12-50',
    category: 'Hardware',
    unitOfMeasure: 'pieces',
    stock: { wh1: 500, wh2: 300, wh3: 200 },
    minStock: 100,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'prod2',
    name: 'Hydraulic Pump HP-2000',
    sku: 'PUMP-HP-2K',
    category: 'Machinery',
    unitOfMeasure: 'units',
    stock: { wh1: 15, wh2: 8, wh3: 12 },
    minStock: 5,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'prod3',
    name: 'Steel Plate 10mm',
    sku: 'STEEL-10MM',
    category: 'Raw Materials',
    unitOfMeasure: 'sheets',
    stock: { wh1: 85, wh2: 45, wh3: 60 },
    minStock: 20,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'prod4',
    name: 'Safety Helmet Industrial',
    sku: 'SAFE-HELM-01',
    category: 'Safety Equipment',
    unitOfMeasure: 'pieces',
    stock: { wh1: 150, wh2: 100, wh3: 80 },
    minStock: 50,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'prod5',
    name: 'Electric Motor 3HP',
    sku: 'MOTOR-3HP',
    category: 'Machinery',
    unitOfMeasure: 'units',
    stock: { wh1: 25, wh2: 10, wh3: 15 },
    minStock: 8,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'prod6',
    name: 'Rubber Gasket Set',
    sku: 'GASKET-RUB-SET',
    category: 'Hardware',
    unitOfMeasure: 'sets',
    stock: { wh1: 220, wh2: 180, wh3: 140 },
    minStock: 100,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'prod7',
    name: 'Industrial Lubricant 5L',
    sku: 'LUB-IND-5L',
    category: 'Chemicals',
    unitOfMeasure: 'bottles',
    stock: { wh1: 95, wh2: 65, wh3: 75 },
    minStock: 40,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'prod8',
    name: 'Cable Reel 100m',
    sku: 'CABLE-100M',
    category: 'Electrical',
    unitOfMeasure: 'reels',
    stock: { wh1: 42, wh2: 28, wh3: 35 },
    minStock: 15,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
  {
    id: 'prod9',
    name: 'Welding Rod E6013',
    sku: 'WELD-E6013',
    category: 'Consumables',
    unitOfMeasure: 'kg',
    stock: { wh1: 180, wh2: 120, wh3: 95 },
    minStock: 50,
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-12'),
  },
  {
    id: 'prod10',
    name: 'Pneumatic Valve V-100',
    sku: 'VALVE-V100',
    category: 'Machinery',
    unitOfMeasure: 'units',
    stock: { wh1: 32, wh2: 18, wh3: 24 },
    minStock: 10,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const initialDeliveries: Delivery[] = [
  {
    id: 'DEL-001',
    warehouseId: 'wh1',
    status: 'done',
    customerName: 'ABC Manufacturing Corp.',
    lines: [
      { productId: 'prod1', quantity: 50 },
      { productId: 'prod4', quantity: 25 },
      { productId: 'prod6', quantity: 10 },
    ],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
    notes: 'Urgent delivery for production line',
  },
  {
    id: 'DEL-002',
    warehouseId: 'wh2',
    status: 'ready',
    customerName: 'XYZ Industrial Solutions',
    lines: [
      { productId: 'prod2', quantity: 2 },
      { productId: 'prod5', quantity: 3 },
    ],
    createdAt: new Date('2024-02-22'),
    updatedAt: new Date('2024-02-23'),
    notes: 'Ready for shipment',
  },
  {
    id: 'DEL-003',
    warehouseId: 'wh1',
    status: 'waiting',
    customerName: 'Tech Components Ltd.',
    lines: [
      { productId: 'prod3', quantity: 15 },
      { productId: 'prod8', quantity: 5 },
      { productId: 'prod9', quantity: 20 },
    ],
    createdAt: new Date('2024-02-24'),
    updatedAt: new Date('2024-02-24'),
  },
  {
    id: 'DEL-004',
    warehouseId: 'wh3',
    status: 'draft',
    customerName: 'Global Machinery Inc.',
    lines: [
      { productId: 'prod7', quantity: 12 },
      { productId: 'prod10', quantity: 4 },
    ],
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
    notes: 'Pending customer confirmation',
  },
  {
    id: 'DEL-005',
    warehouseId: 'wh2',
    status: 'done',
    customerName: 'Premium Parts Distributors',
    lines: [
      { productId: 'prod1', quantity: 100 },
      { productId: 'prod6', quantity: 20 },
      { productId: 'prod4', quantity: 30 },
    ],
    createdAt: new Date('2024-02-18'),
    updatedAt: new Date('2024-02-19'),
  },
  {
    id: 'DEL-006',
    warehouseId: 'wh3',
    status: 'canceled',
    customerName: 'Small Business Supply Co.',
    lines: [
      { productId: 'prod5', quantity: 2 },
    ],
    createdAt: new Date('2024-02-21'),
    updatedAt: new Date('2024-02-21'),
    notes: 'Customer canceled order',
  },
];

export const initialTransfers: Transfer[] = [
  {
    id: 'TRF-001',
    fromWarehouseId: 'wh1',
    toWarehouseId: 'wh2',
    status: 'done',
    lines: [
      { productId: 'prod1', quantity: 100 },
      { productId: 'prod4', quantity: 50 },
    ],
    createdAt: new Date('2024-02-19'),
    updatedAt: new Date('2024-02-19'),
    notes: 'Stock rebalancing for North DC',
  },
  {
    id: 'TRF-002',
    fromWarehouseId: 'wh2',
    toWarehouseId: 'wh3',
    status: 'ready',
    lines: [
      { productId: 'prod2', quantity: 3 },
      { productId: 'prod5', quantity: 5 },
      { productId: 'prod10', quantity: 2 },
    ],
    createdAt: new Date('2024-02-23'),
    updatedAt: new Date('2024-02-23'),
    notes: 'Transfer to South Hub for upcoming orders',
  },
  {
    id: 'TRF-003',
    fromWarehouseId: 'wh1',
    toWarehouseId: 'wh3',
    status: 'waiting',
    lines: [
      { productId: 'prod3', quantity: 20 },
      { productId: 'prod7', quantity: 15 },
      { productId: 'prod8', quantity: 10 },
    ],
    createdAt: new Date('2024-02-24'),
    updatedAt: new Date('2024-02-24'),
  },
  {
    id: 'TRF-004',
    fromWarehouseId: 'wh3',
    toWarehouseId: 'wh1',
    status: 'draft',
    lines: [
      { productId: 'prod9', quantity: 30 },
      { productId: 'prod6', quantity: 15 },
    ],
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
    notes: 'Return transfer for quality check',
  },
  {
    id: 'TRF-005',
    fromWarehouseId: 'wh2',
    toWarehouseId: 'wh1',
    status: 'done',
    lines: [
      { productId: 'prod1', quantity: 50 },
      { productId: 'prod4', quantity: 25 },
    ],
    createdAt: new Date('2024-02-17'),
    updatedAt: new Date('2024-02-17'),
  },
  {
    id: 'TRF-006',
    fromWarehouseId: 'wh1',
    toWarehouseId: 'wh2',
    status: 'canceled',
    lines: [
      { productId: 'prod2', quantity: 2 },
    ],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
    notes: 'Transfer canceled - insufficient stock',
  },
];
